version: "3.8"

services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: rahul
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: stockdatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql


  app:
    build:
      context: .                 # root
      dockerfile: airflow/scripts/Dockerfile
    container_name: python_app
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - .:/app
    command: python airflow/scripts/table_insertion.py

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"

volumes:
  postgres_data:
